services:
  portfolio:
    image: ghcr.io/randriamasinoro/portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production